[project]
name = "student-performance"
version = "0.1.0"
description = "Student Performance Analysis and Model Training"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "setuptools>=80.3.1",
]
